name: Build XZ for Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Android NDK
      run: |
        mkdir -p $HOME/android-ndk
        curl -sSL https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o android-ndk.zip
        unzip android-ndk.zip -d $HOME/android-ndk
        export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25c
        echo "ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r25c" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Configure and build XZ Utils for Android
      env:
        ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=arm64-v8a \
              -DANDROID_PLATFORM=android-21 ..
        make

   # - name: Upload binary artifact
   #   uses: actions/upload-artifact@v3
   #   with:
   #    name: xz-android-binary
   #     path: build/src/xz
